### PR TITLE
Feature/events

### PR DESCRIPTION
**Pull request by andrii-chykharivskyi**

### CODE REVIEW

**Review by sliderif — COMMENTED** [review]
Remove .idea directory from repository

**Review by sliderif — COMMENTED** [review]
api crud implementation missing

**Review by sliderif — COMMENTED** [review]
Add soft deletes

**Review by sliderif — COMMENTED** [review]
Implent full entity models, as in eloquent model convention - https://laravel.com/docs/5.4/eloquent#eloquent-model-conventions

**Comment by andrii-chykharivskyi** [comment]
@sliderif Pls, review last commits. https://laravel.com/docs/5.1/controllers#restful-resource-controllers it is that we need to develope controllers?

**Comment by sliderif** [comment]
It's better to create request classes instead of using raw, especially for validation purposes, request objects. Everething else seems good

**Pull request merged**
